// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Beagl.WebApp.Resources.Pages.Animals
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateCat
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateCat()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beagl.WebApp.Resources.Pages.Animals.CreateCat", typeof(CreateCat).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Error_Required_Name => ResourceManager.GetString("Error_Required_Name", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Breed.
        /// </summary>
        public static string Error_Required_BreedPrimaryId => ResourceManager.GetString("Error_Required_BreedPrimaryId", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Color.
        /// </summary>
        public static string Error_Required_ColorId => ResourceManager.GetString("Error_Required_ColorId", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Gender.
        /// </summary>
        public static string Error_Required_Gender => ResourceManager.GetString("Error_Required_Gender", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Error_Required_BirthDate => ResourceManager.GetString("Error_Required_BirthDate", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Weight.
        /// </summary>
        public static string Error_Required_Weight => ResourceManager.GetString("Error_Required_Weight", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Weight Unit.
        /// </summary>
        public static string Error_Required_WeightUnit => ResourceManager.GetString("Error_Required_WeightUnit", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Is An Unclawned Cat.
        /// </summary>
        public static string Error_Required_IsAnUnclawnedCat => ResourceManager.GetString("Error_Required_IsAnUnclawnedCat", resourceCulture);

        /// <summary>
        /// Looks up a localized string similar to Medal.
        /// </summary>
        public static string Error_Required_Medal => ResourceManager.GetString("Error_Required_Medal", resourceCulture);
    }
}
