// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Beagl.WebApp.Resources.Pages.Citizens
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beagl.WebApp.Resources.Pages.Citizens.Create", typeof(Create).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        public static string FirstName_Required => ResourceManager.GetString("FirstName_Required", resourceCulture);
        public static string LastName_Required => ResourceManager.GetString("LastName_Required", resourceCulture);
        public static string CommunicationPreference_Required => ResourceManager.GetString("CommunicationPreference_Required", resourceCulture);
        public static string LanguagePreference_Required => ResourceManager.GetString("LanguagePreference_Required", resourceCulture);
        public static string StreetNumber_Required => ResourceManager.GetString("StreetNumber_Required", resourceCulture);
        public static string StreetName_Required => ResourceManager.GetString("StreetName_Required", resourceCulture);
        public static string City_Required => ResourceManager.GetString("City_Required", resourceCulture);
        public static string Province_Required => ResourceManager.GetString("Province_Required", resourceCulture);
        public static string Country_Required => ResourceManager.GetString("Country_Required", resourceCulture);
        public static string PostalCode_Required => ResourceManager.GetString("PostalCode_Required", resourceCulture);
        public static string StreetAddress_Required => ResourceManager.GetString("StreetAddress_Required", resourceCulture);
        public static string Email_Required => ResourceManager.GetString("Email_Required", resourceCulture);
        public static string PhoneFormat_Invalid => ResourceManager.GetString("PhoneFormat_Invalid", resourceCulture);
        public static string CellPhoneFormat_Invalid => ResourceManager.GetString("CellPhoneFormat_Invalid", resourceCulture);

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }
}
