// <auto-generated />
using System;
using Beagl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beagl.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016142148_UpdateAnimalAggregateRoot")]
    partial class UpdateAnimalAggregateRoot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistinctiveDescription")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnAssistanceDog")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAnUnclawnedCat")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Entities.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSterilized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RabiesVaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Entities.MedalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedalNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("MedalRecords");
                });

            modelBuilder.Entity("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Animal", b =>
                {
                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Created", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedByUserId");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Modified", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Breed", "Breed", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Primary")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PrimaryBreed");

                            b1.Property<string>("Secondary")
                                .HasColumnType("text")
                                .HasColumnName("SecondaryBreed");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.DangerousDog", "DangerousDog", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comment")
                                .HasColumnType("text")
                                .HasColumnName("DangerousDogComment");

                            b1.Property<bool>("HasResponsibilityInsurance")
                                .HasColumnType("boolean")
                                .HasColumnName("HasDangerousDogInsurance");

                            b1.Property<bool>("IsDangerous")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDangerousDog");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Gender", "Gender", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Gender");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Microchip", "Microchip", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Microchip");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.OriginCityInfo", "OriginCityInfo", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("ComesFromAnotherCity")
                                .HasColumnType("boolean")
                                .HasColumnName("ComesFromAnotherCity");

                            b1.Property<bool>("HadJudgmentInThatCity")
                                .HasColumnType("boolean")
                                .HasColumnName("HadJudgmentInThatCity");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Photo", "Photo", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Base64Png")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhotoBase64Png");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.Navigation("Breed")
                        .IsRequired();

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("DangerousDog");

                    b.Navigation("Gender")
                        .IsRequired();

                    b.Navigation("Microchip");

                    b.Navigation("Modified");

                    b.Navigation("OriginCityInfo");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Entities.HealthRecord", b =>
                {
                    b.HasOne("Beagl.Domain.AnimalManagement.Animal", "Animal")
                        .WithMany("HealthRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Created", b1 =>
                        {
                            b1.Property<Guid>("HealthRecordId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedByUserId");

                            b1.HasKey("HealthRecordId");

                            b1.ToTable("HealthRecords");

                            b1.WithOwner()
                                .HasForeignKey("HealthRecordId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Modified", b1 =>
                        {
                            b1.Property<Guid>("HealthRecordId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("HealthRecordId");

                            b1.ToTable("HealthRecords");

                            b1.WithOwner()
                                .HasForeignKey("HealthRecordId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("HealthRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("WeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("WeightValue");

                            b1.HasKey("HealthRecordId");

                            b1.ToTable("HealthRecords");

                            b1.WithOwner()
                                .HasForeignKey("HealthRecordId");
                        });

                    b.Navigation("Animal");

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Entities.MedalRecord", b =>
                {
                    b.HasOne("Beagl.Domain.AnimalManagement.Animal", "Animal")
                        .WithMany("MedalRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Beagl.Domain.AnimalManagement.Entities.MedalRecord.Created#Audit", "Created", b1 =>
                        {
                            b1.Property<Guid>("MedalRecordId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedByUserId");

                            b1.HasKey("MedalRecordId");

                            b1.ToTable("MedalRecords");

                            b1.WithOwner()
                                .HasForeignKey("MedalRecordId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Modified", b1 =>
                        {
                            b1.Property<Guid>("MedalRecordId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("MedalRecordId");

                            b1.ToTable("MedalRecords");

                            b1.WithOwner()
                                .HasForeignKey("MedalRecordId");
                        });

                    b.Navigation("Animal");

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beagl.Domain.AnimalManagement.Animal", b =>
                {
                    b.Navigation("HealthRecords");

                    b.Navigation("MedalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
