// <auto-generated />
using System;
using Beagl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beagl.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistinctiveDescription")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrimaryBreedId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpeciesType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("PrimaryBreedId");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.BreedModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SpeciesType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.ColorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SpeciesType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.CatModel", b =>
                {
                    b.HasBaseType("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel");

                    b.Property<bool>("IsAnUnclawnedCat")
                        .HasColumnType("boolean");

                    b.ToTable("Cats", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.DogModel", b =>
                {
                    b.HasBaseType("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel");

                    b.Property<bool>("IsAnAssistanceDog")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SecondaryBreedId")
                        .HasColumnType("uuid");

                    b.HasIndex("SecondaryBreedId");

                    b.ToTable("Dogs", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel", b =>
                {
                    b.HasOne("Beagl.Infrastructure.AnimalManagement.Models.ColorModel", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Beagl.Infrastructure.AnimalManagement.Models.BreedModel", "PrimaryBreed")
                        .WithMany()
                        .HasForeignKey("PrimaryBreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Microchip", "Microchip", b1 =>
                        {
                            b1.Property<Guid>("AnimalModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Microchip");

                            b1.HasKey("AnimalModelId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalModelId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("AnimalModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("WeightUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Weight");

                            b1.HasKey("AnimalModelId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalModelId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Photo", "Photo", b1 =>
                        {
                            b1.Property<Guid>("AnimalModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("base64Png")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhotoBase64Png");

                            b1.HasKey("AnimalModelId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalModelId");
                        });

                    b.OwnsOne("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel.Created#Audit", "Created", b1 =>
                        {
                            b1.Property<Guid>("AnimalModelId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("at")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("userId")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedByUserId");

                            b1.HasKey("AnimalModelId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalModelId");
                        });

                    b.OwnsOne("Beagl.Domain.Core.ValueObjects.Audit<System.Guid>", "Modified", b1 =>
                        {
                            b1.Property<Guid>("AnimalModelId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("at")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("userId")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("AnimalModelId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalModelId");
                        });

                    b.Navigation("Color");

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Microchip");

                    b.Navigation("Modified");

                    b.Navigation("Photo");

                    b.Navigation("PrimaryBreed");

                    b.Navigation("Weight")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.UserManagement.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.CatModel", b =>
                {
                    b.HasOne("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Beagl.Infrastructure.AnimalManagement.Models.CatModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beagl.Infrastructure.AnimalManagement.Models.DogModel", b =>
                {
                    b.HasOne("Beagl.Infrastructure.AnimalManagement.Models.AnimalModel", null)
                        .WithOne()
                        .HasForeignKey("Beagl.Infrastructure.AnimalManagement.Models.DogModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beagl.Infrastructure.AnimalManagement.Models.BreedModel", "SecondaryBreed")
                        .WithMany()
                        .HasForeignKey("SecondaryBreedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.DangerousDog", "DangerousDog", b1 =>
                        {
                            b1.Property<Guid>("DogModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("comment")
                                .HasColumnType("text")
                                .HasColumnName("DangerousDogComment");

                            b1.Property<bool>("hasResponsibilityInsurance")
                                .HasColumnType("boolean")
                                .HasColumnName("HasDangerousDogInsurance");

                            b1.Property<bool>("isDangerous")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDangerousDog");

                            b1.HasKey("DogModelId");

                            b1.ToTable("Dogs");

                            b1.WithOwner()
                                .HasForeignKey("DogModelId");
                        });

                    b.OwnsOne("Beagl.Domain.AnimalManagement.ValueObjects.OriginCityInfo", "OriginCityInfo", b1 =>
                        {
                            b1.Property<Guid>("DogModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("cityName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("comesFromAnotherCity")
                                .HasColumnType("boolean")
                                .HasColumnName("ComesFromAnotherCity");

                            b1.Property<bool>("hadJudgmentInThatCity")
                                .HasColumnType("boolean")
                                .HasColumnName("HadJudgmentInThatCity");

                            b1.HasKey("DogModelId");

                            b1.ToTable("Dogs");

                            b1.WithOwner()
                                .HasForeignKey("DogModelId");
                        });

                    b.Navigation("DangerousDog");

                    b.Navigation("OriginCityInfo");

                    b.Navigation("SecondaryBreed");
                });
#pragma warning restore 612, 618
        }
    }
}
