name: Versionize Release

on:
  push:
    branches:
      - chore/dockerize-and-versionize

jobs:
  versionize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Configure git for versionize commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Versionize
        run: versionize

      - name: Push version bump and changelog
        run: |
          git add .
          git commit -m "chore(release): bump version and update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
